spring.application.name=campus-placement-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/campus_tracker
spring.datasource.username=root
spring.datasource.password=Adity@2175

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true